from __future__ import annotations

from app.config import PAPER_BANK_BASELINE, PAPER_STAKE_PCT
from app.models import PaperBet, PaperBetArchive, PaperBankReset

STARTING_BANK = PAPER_BANK_BASELINE
STAKE_PERCENT = PAPER_STAKE_PCT


def get_latest_reset(db) -> PaperBankReset | None:
    return db.query(PaperBankReset).order_by(PaperBankReset.id.desc()).first()


def get_bank_baseline(db) -> float:
    latest_reset = get_latest_reset(db)
    if latest_reset and latest_reset.baseline_bank is not None:
        return float(latest_reset.baseline_bank)
    return float(STARTING_BANK)


def get_current_bank(db) -> float:
    """Return the current paper bank after settled profit and loss."""
    settled_bets = db.query(PaperBet).filter(PaperBet.profit_loss.isnot(None)).all()
    profit_loss_total = sum(bet.profit_loss for bet in settled_bets)
    return round(get_bank_baseline(db) + profit_loss_total, 2)


def get_bank_since_reset(db) -> float:
    """Return profit/loss generated by the active paper-betting cycle."""
    current_bank = get_current_bank(db)
    return round(current_bank - get_bank_baseline(db), 2)


def get_lifetime_bank(db) -> float:
    """Return a lifetime-style bank including archived cycles."""
    active_profit_loss = sum(
        (bet.profit_loss or 0.0)
        for bet in db.query(PaperBet).filter(PaperBet.profit_loss.isnot(None)).all()
    )
    archived_profit_loss = sum(
        (bet.profit_loss or 0.0)
        for bet in db.query(PaperBetArchive).filter(PaperBetArchive.profit_loss.isnot(None)).all()
    )
    return round(STARTING_BANK + active_profit_loss + archived_profit_loss, 2)


def get_next_stake(db) -> float:
    """Return the next stake using a conservative percentage of the current bank."""
    current_bank = get_current_bank(db)
    return round(current_bank * STAKE_PERCENT, 2)


def get_total_roi(db) -> float:
    """Return total ROI as settled profit/loss divided by total settled stake."""
    settled_bets = db.query(PaperBet).filter(PaperBet.profit_loss.isnot(None)).all()
    total_staked = sum(bet.stake for bet in settled_bets)
    if total_staked <= 0:
        return 0.0

    total_profit_loss = sum(bet.profit_loss for bet in settled_bets)
    return round(total_profit_loss / total_staked, 4)
